version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Initializing environment...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 905418287014 --region us-east-2 --query authorizationToken --output text)

  build:
    commands:
      - echo Build started on `date`
      - mvn clean compile -s settings.xml -U  # -U forces dependency updates

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package -s settings.xml -U

artifacts:
  files:
    - target/nextwork-web-project.war
  discard-paths: no
